/**
 * File: src/utility/searchSocialInfo.js
 * Description: data for search and social section.
 * Data: 24/03/2023
 * Author: Renu singroha
 */
export const SEARCH_SOCIAL_INFO = [
    {
        id:1,
        heading:"Web Design and Development",
        para:"Web design is a medium that reflects the value you are adding as a business.",
        button:"Discover"
    },
    {
        id:2,
        heading:"Social Media Marketing",
        para:"Social media channels have become a major source of news and information in today’s internet-driven world. ",
        button:"Discover"
    },
    {
        id:3,
        heading:"Search Engine Optimization (SEO)",
        para:"Rank in the top of search engines. Local SEO, link building. and more.",
        button:"Discover"
    },
    {
        id:4,
        heading:"Search Engine Marketing (SEM)",
        para:"Partner with pros for your pay-per-click campaigns on Google, Bing and Yahoo!",
        button:"Discover"
    },
    {
        id:5,
        heading:"Pay Per Click Advertising",
        para:"Get instant results with our pay per click (PPC) system.",
        button:"Discover"
    },
    {
        id:6,
        heading:"Photography & Video Marketing",
        para:"Brand videos are powerful tools for any content strategy.",
        button:"Discover"
    },
    {
        id:7,
        heading:"Email Marketing",
        para:"Stay top of mind with one of the most creative email marketing campaigns.",
        button:"Discover"
    },
    {
        id:8,
        heading:"Affiliate Marketing",
        para:"Affiliate marketing is an advertising model based on third-party publishers to generate traffic or leads. ",
        button:"Discover"
    },
    {
        id:9,
        heading:"Branding",
        para:"A brand values and the identity you want the world to remember you with as a brand.",
        button:"Discover"
    },
    {
        id:10,
        heading:"Content Marketing and Curation",
        para:"We can be your company voice with quality content generated by our content writing team.",
        button:"Discover"
    }
];