/**
 * File: src/utility/serviceCardInfo.js
 * Description: data for service card.
 * Data: 16/03/2023
 * Author: Renu singroha
 */
export const SERVICE_CARD_INFO = [
    {
        id:1,
        img:"/images/advertise/service-1.png",
        heading:"Web Design and Development",
        para:"Web design is a medium that reflects the value you are adding as a business.",
    },
    {
        id:2,
        img:"/images/advertise/service-1.png",
        heading:"Social Media Marketing",
        para:"Social media channels have become a major source of news and information in today’s internet-driven world. ",
    },
    {
        id:3,
        img:"/images/advertise/service-1.png",
        heading:"Search Engine Optimization (SEO)",
        para:"Rank in the top of search engines. Local SEO, link building. and more.",
    },
    {
        id:4,
        img:"/images/advertise/service-1.png",
        heading:"Search Engine Marketing (SEM)",
        para:"Partner with pros for your pay-per-click campaigns on Google, Bing and Yahoo!",
    },
    {
        id:5,
        img:"/images/advertise/service-1.png",
        heading:"Pay Per Click Advertising",
        para:"Get instant results with our pay per click (PPC) system.",
    },
    {
        id:6,
        img:"/images/advertise/service-1.png",
        heading:"Photography & Video Marketing",
        para:"Brand videos are powerful tools for any content strategy.",
    },
    {
        id:7,
        img:"/images/advertise/service-1.png",
        heading:"Email Marketing",
        para:"Stay top of mind with one of the most creative email marketing campaigns.",
    },
    {
        id:8,
        img:"/images/advertise/service-1.png",
        heading:"Affiliate Marketing",
        para:"Affiliate marketing is an advertising model based on third-party publishers to generate traffic or leads. ",
    },
    {
        id:9,
        img:"/images/advertise/service-1.png",
        heading:"Branding",
        para:"A brand values and the identity you want the world to remember you with as a brand.",
    },
    {
        id:10,
        img:"/images/advertise/service-1.png",
        heading:"Content Marketing and Curation",
        para:"We can be your company voice with quality content generated by our content writing team.",
    },
    {
        id:11,
        img:"/images/advertise/service-1.png",
        heading:"Web & Email Hosting",
        para:"Choose to lay a robust foundation for your website with fast and secure web and email hosting services.",
    },
    {
        id:12,
        img:"/images/advertise/service-1.png",
        heading:"Dedicated Graphic Design",
        para:"Strong graphic elements can be useful in directing viewers' attention and providing structure for the page. It communicates the brand value as well to the target audience.",
    }
];