import Head from "next/head";
import Layout from "@/src/layouts/Layout";
import HomeBanner from "@/src/components/home/HomeBanner";
import Index from "@/src/components/map";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeBanner />
        <Index />
      </Layout>
    </>
  );
}
